// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web not configured');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCHA9p-N6xJJgmb4iZVCT6mVblVL8DY-g', // Aynı Proje API Key
    appId: '1:832274027170:android:20e9608722e5cb69003dfb', // JSON içindeki yeni App ID
    messagingSenderId: '832274027170',
    projectId: 'su-hatirlatici-455b2',
    storageBucket: 'su-hatirlatici-455b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHA9p-N6xJJgmb4iZVCT6mVblVL8DY-g',
    appId: '1:832274027170:ios:2c0c98601f3d7243003dfb',
    messagingSenderId: '832274027170',
    projectId: 'su-hatirlatici-455b2',
    storageBucket: 'su-hatirlatici-455b2.firebasestorage.app',
    iosBundleId: 'com.cervus.suhatirlatici',
  );
}
