// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjIf0ACCfQtTpmml3lNte7zDRYvGMRr4',
    appId: '1:832274027170:web:9ad1aa9b6cfbfbae003dfb',
    messagingSenderId: '832274027170',
    projectId: 'su-hatirlatici-455b2',
    authDomain: 'su-hatirlatici-455b2.firebaseapp.com',
    storageBucket: 'su-hatirlatici-455b2.firebasestorage.app',
    measurementId: 'G-BW305B4QBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYTNdzbm3kXfwOr4k7skFOIV7xP9YirP4',
    appId: '1:832274027170:android:20e9608722e5cb69003dfb',
    messagingSenderId: '832274027170',
    projectId: 'su-hatirlatici-455b2',
    storageBucket: 'su-hatirlatici-455b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHA9p-N6xJJgmb4iZVCT6mVblVL8DY-g',
    appId: '1:832274027170:ios:de7082ebcdf486fe003dfb',
    messagingSenderId: '832274027170',
    projectId: 'su-hatirlatici-455b2',
    storageBucket: 'su-hatirlatici-455b2.firebasestorage.app',
    iosBundleId: 'com.cervus.suhatirlatici.suhatirlatici',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCHA9p-N6xJJgmb4iZVCT6mVblVL8DY-g',
    appId: '1:832274027170:ios:de7082ebcdf486fe003dfb',
    messagingSenderId: '832274027170',
    projectId: 'su-hatirlatici-455b2',
    storageBucket: 'su-hatirlatici-455b2.firebasestorage.app',
    iosBundleId: 'com.cervus.suhatirlatici.suhatirlatici',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjIf0ACCfQtTpmml3lNte7zDRYvGMRr4',
    appId: '1:832274027170:web:5636a3690c66fda7003dfb',
    messagingSenderId: '832274027170',
    projectId: 'su-hatirlatici-455b2',
    authDomain: 'su-hatirlatici-455b2.firebaseapp.com',
    storageBucket: 'su-hatirlatici-455b2.firebasestorage.app',
    measurementId: 'G-GBBVSGSV61',
  );
}
